version: '3.8'

services:
  # Runner 1
  runner-1:
    image: ghcr.io/handyshed/github-actions-runner:latest
    container_name: github-runner-1
    environment:
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=container-runner-1
      - RUNNER_LABELS=self-hosted,Linux,X64,containerized,playwright
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/runner/externals:/home/runner/externals
    restart: unless-stopped

  # Runner 2
  runner-2:
    image: ghcr.io/handyshed/github-actions-runner:latest
    container_name: github-runner-2
    environment:
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=container-runner-2
      - RUNNER_LABELS=self-hosted,Linux,X64,containerized,playwright
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/runner/externals:/home/runner/externals
    restart: unless-stopped

  # Runner 3
  runner-3:
    image: ghcr.io/handyshed/github-actions-runner:latest
    container_name: github-runner-3
    environment:
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=container-runner-3
      - RUNNER_LABELS=self-hosted,Linux,X64,containerized,playwright
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/runner/externals:/home/runner/externals
    restart: unless-stopped

# Note: All runners share the same host externals directory for efficiency
# The first runner to start will initialize the toolcache for all others